---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  collections:
    - f5networks.f5_modules
    
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "8443"
        validate_certs: "False"

    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ansible_host}}"
        server_port: "{{server_port}}"
        validate_certs: "False"
      when: server_port is defined
      
    - name: ADD iRules
      f5networks.f5_modules.bigip_irule:
        provider: "{{provider}}"
        module: "ltm"
        name: "irule1"
        content: "{{lookup('file','irule1')}}"

    - name: ATTACH iRules TO VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{provider}}"
        name: "vip"
        irules: "irule1"
