---
- name: GRAB F5 FACTS
  hosts: f5
  connection: local
  gather_facts: false

  collections:
    - f5networks.f5_modules

  tasks:

    - name: Setting up provider values
      set_fact:
       provider:
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server: "{{private_ip}}"
        server_port: "8443"
        validate_certs: "False"

    - name: Setting up provider values
      set_fact:
       provider:
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server: "{{ansible_host}}"
        server_port: "{{server_port}}"
        validate_certs: "False"
      when: server_port is defined

    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
          - system-info
        provider: "{{provider}}"
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts

    - name: DISPLAY ONLY THE MAC ADDRESS
      debug:
        var: device_facts['system_info']['base_mac_address']

    - name: DISPLAY ONLY THE VERSION
      debug:
        var: device_facts['system_info']['product_version']
